steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '-ldflags', "'-w'", './cmd/v1/api']
  env: ["PROJECT_ROOT=github.com/harlow/go-micro-services", "CGO_ENABLED=0", "GOOS=linux"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file', 'Dockerfile.api', '--tag=gcr.io/$PROJECT_ID/api-v1', '.']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '-ldflags', "'-w'", './cmd/v1/geo']
  env: ["PROJECT_ROOT=github.com/harlow/go-micro-services", "CGO_ENABLED=0", "GOOS=linux"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file', 'Dockerfile.geo', '--tag=gcr.io/$PROJECT_ID/geo-v1', '.']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '-ldflags', "'-w'", './cmd/v1/profile']
  env: ["PROJECT_ROOT=github.com/harlow/go-micro-services", "CGO_ENABLED=0", "GOOS=linux"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file', 'Dockerfile.profile', '--tag=gcr.io/$PROJECT_ID/profile-v1', '.']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '-ldflags', "'-w'", './cmd/v1/rate']
  env: ["PROJECT_ROOT=github.com/harlow/go-micro-services", "CGO_ENABLED=0", "GOOS=linux"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file', 'Dockerfile.rate', '--tag=gcr.io/$PROJECT_ID/rate-v1', '.']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '-ldflags', "'-w'", './cmd/v1/search']
  env: ["PROJECT_ROOT=github.com/harlow/go-micro-services", "CGO_ENABLED=0", "GOOS=linux"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file', 'Dockerfile.search', '--tag=gcr.io/$PROJECT_ID/search-v1', '.']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '-ldflags', "'-w'", './cmd/v1/www']
  env: ["PROJECT_ROOT=github.com/harlow/go-micro-services", "CGO_ENABLED=0", "GOOS=linux"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file', 'Dockerfile.www', '--tag=gcr.io/$PROJECT_ID/www-v1', '.']
images: ['gcr.io/$PROJECT_ID/api-v1', 'gcr.io/$PROJECT_ID/geo-v1', 'gcr.io/$PROJECT_ID/profile-v1', 'gcr.io/$PROJECT_ID/rate-v1', 'gcr.io/$PROJECT_ID/search-v1', 'gcr.io/$PROJECT_ID/www-v1']
